### ISSUE TITLE
Unable to turn off my MagicMirror

### ISSUE THREAD

**Issue by Baassievalk** [mlbonniec/MMM-HomeKit#3]
When turning on my MagicMirror i'm getting the following log: 

`sudo: no terminal available and no  passwordask(askpass) programs gave up.`

I had to translate it so it won't be spot on!

**Comment by Baassievalk** [comment]
After putting this in the HomeBridge Terminal: `tvservice --preferred && sudo chvt 6 && sudo chvt 7`
I got this:

```
Powering on HDMI with preferred settings
chvt: ioctl VT_ACTIVATE: Action is not allowed.
```
Instead of the usual:
`sudo: no terminal available and no passwordask(askpass) programs gave up.`

I hope this is progress.

**Comment by mlbonniec** [comment]
Hi! Thanks for reporting your issue.
Did you try to perform these commands directly in your Raspberry terminal?
`tvservice --preferred && sudo chvt 6 && sudo chvt 7`
And also which Raspberry do you own?

**Comment by Baassievalk** [comment]
Hi! 
I own a Raspberry Pi 4 Model B 4Gb

running:
`tvservice --preferred && sudo chvt 6 && sudo chvt 7` 
in my Raspberry terminal works.

**Comment by BKeyport** [comment]
This is actually not a homebridge issue, rather, a configuration issue within the command software and/or RPi issue. I highly recommend using vcgencmd instead.

```
{
           "platform": "cmdSwitch2",
           "name": "Raspberry Pi",
           "switches": [
               {
                   "name": "Mirror",
                   "on_cmd": "vcgencmd display_power 1",
                   "off_cmd": "vcgencmd display_power 0",
                   "state_cmd": "vcgencmd display_power | grep -i 'display_power=1'",    
                    "manufacturer": "Raspberry Pi Foundation",
                   "model": "Raspberry Pi 3 Model B"
               }
           ]
       }
   ]
}
```
